[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
    | venv
    | _build
    | buck-out
    | build
    | dist
    | test_data
    | migrations
    | config/settings.py
  )/
)
'''