# Generated by Django 3.2.7 on 2021-09-04 20:42

from django.db import migrations, models
import django.db.models.deletion
import lubimovka.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 40 символов', max_length=40, verbose_name='Имя')),
                ('surname', models.CharField(help_text='Не более 40 символов', max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(help_text='Не более 40 символов', max_length=40, verbose_name='Отчество')),
                ('position', models.CharField(help_text='Не более 40 символов', max_length=40, verbose_name='Должность')),
                ('work_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Рабочий номер телефона')),
                ('personal_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Личный номер телефона')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Факс')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Не более 40 символов', max_length=40, unique=True, verbose_name='Название')),
                ('address', models.CharField(help_text='Не более 40 символов', max_length=40, verbose_name='Адрес')),
                ('description', models.TextField(help_text='Краткое описание', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmployeeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lubimovka.employee', verbose_name='Сотрудник')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lubimovka.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудник в организации',
                'verbose_name_plural': 'Сотрудники в организации',
                'unique_together': {('employee', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='employees',
            field=models.ManyToManyField(through='lubimovka.OrganizationEmployeeRelation', to='lubimovka.Employee'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', lubimovka.models.UserManager()),
            ],
        ),
    ]
